### get info
GET http://localhost:3001/api/persons/info

### get all
GET http://localhost:3001/api/persons   

### get single resource (hitler)
GET http://localhost:3001/api/persons/66ccc1297b8a64575a0d0f5c

### delete resource
DELETE http://localhost:3001/api/persons/66cce270db21a44c7ad7d183

### create resource
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "lipo hellmuth",
    "phoneNumber": "12-149-8675",
    "userId": "66db4862ed6db5cabc46796f"
}

### update resource(hitler)
PUT http://localhost:3001/api/persons/66ccc1297b8a64575a0d0f5c
Content-Type: application/json

{
    "name" : "Hitler",
    "phoneNumber": "000-0000000-00"
}