### get info
GET http://localhost:3001/api/persons/info

### get all
GET http://localhost:3001/api/persons   

### get single resource (hitler)
GET http://localhost:3001/api/persons/66ccc1297b8a64575a0d0f5c

### delete resource
DELETE http://localhost:3001/api/persons/66cce270db21a44c7ad7d183

### create resource
POST http://localhost:3001/api/persons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhyLW5tbSIsImlkIjoiNjZkNWZmMzI2Mjg4M2JiZWJmZmE4ZDc1IiwiaWF0IjoxNzI1NzMzODQzLCJleHAiOjE3MjU3Mzc0NDN9.Y6ING-6a5DmNGTmOt6FmbQOJgpab2b3PueC1Evt4xxQ

{
    "name" : "new phoneno with token hellmuth",
    "phoneNumber": "88-149-8675"
}

### update resource(hitler)
PUT http://localhost:3001/api/persons/66ccc1297b8a64575a0d0f5c
Content-Type: application/json

{
    "name" : "Hitler",
    "phoneNumber": "000-0000000-00"
}