### get all users
GET http://localhost:3001/api/users

### create user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "root",
    "passwordHash": "youknowme"
}